name = "projection"
version = "0.1.0"
license = "license"

author = "xiaolh"
maintainer = "xiaolh@3clear.com"
copyright = "Copyright 2024, xiaolh"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"

